app = "rabbitmq"

[build]

# rabbitmq main
[[services]]
    http_checks = []
    internal_port = 5672
    protocol = "tcp"
    script_checks = []

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "60s"

# rabbitmq admin
[[services]]
    http_checks = []
    internal_port = 15672
    protocol = "tcp"
    script_checks = []

[[services.ports]]
    handlers = ["tls", "http"]
    port = "15672"

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "60s"
