app = "calculator-api"

[build]
dockerfile = "Dockerfile"

[env]
ASPNETCORE_URLS = "http://+:8080"
RABBITMQ__HOST = "rabbitmq.internal"
RABBITMQ__PORT = "5672"

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]
